import { Routes } from '@angular/router';

export const COMPONENTS_SHOWCASE_ROUTES: Routes = [
  { path: '', redirectTo: 'button', pathMatch: 'full' },
  { path: 'button', loadComponent: () => import('./components/button.component').then(m => m.ButtonSectionComponent) },
  { path: 'input', loadComponent: () => import('./components/input.component').then(m => m.InputSectionComponent) },
  { path: 'textarea', loadComponent: () => import('./components/textarea.component').then(m => m.TextareaSectionComponent) },
  { path: 'select', loadComponent: () => import('./components/select.component').then(m => m.SelectSectionComponent) },
  { path: 'checkbox', loadComponent: () => import('./components/checkbox.component').then(m => m.CheckboxSectionComponent) },
  { path: 'radio', loadComponent: () => import('./components/radio.component').then(m => m.RadioSectionComponent) },
  { path: 'switch', loadComponent: () => import('./components/switch.component').then(m => m.SwitchSectionComponent) },
  { path: 'card', loadComponent: () => import('./components/card.component').then(m => m.CardSectionComponent) },
  { path: 'toolbar', loadComponent: () => import('./components/toolbar.component').then(m => m.ToolbarSectionComponent) },
  { path: 'sidenav', loadComponent: () => import('./components/sidenav.component').then(m => m.SidenavSectionComponent) },
  { path: 'menu', loadComponent: () => import('./components/menu.component').then(m => m.MenuSectionComponent) },
  { path: 'dialog', loadComponent: () => import('./components/dialog.component').then(m => m.DialogSectionComponent) },
  { path: 'snackbar', loadComponent: () => import('./components/snackbar.component').then(m => m.SnackbarSectionComponent) },
  { path: 'table', loadComponent: () => import('./components/table.component').then(m => m.TableSectionComponent) },
  { path: 'core', loadComponent: () => import('../pages/core/core.component').then(m => m.PageCoreComponent) },
  { path: 'ripples', loadComponent: () => import('../pages/ripples/ripples.component').then(m => m.PageRipplesComponent) },
  { path: 'slidetoggle', loadComponent: () => import('../pages/slidetoggle/slidetoggle.component').then(m => m.PageSlideToggleComponent) },
  { path: 'slider', loadComponent: () => import('../pages/slider/slider.component').then(m => m.PageSliderComponent) },
  { path: 'sortheader', loadComponent: () => import('../pages/sortheader/sortheader.component').then(m => m.PageSortHeaderComponent) },
  { path: 'stepper', loadComponent: () => import('../pages/stepper/stepper.component').then(m => m.PageStepperComponent) },
  { path: 'tabs', loadComponent: () => import('../pages/tabs/tabs.component').then(m => m.PageTabsComponent) },
  { path: 'timepicker', loadComponent: () => import('../pages/timepicker/timepicker.component').then(m => m.PageTimepickerComponent) },
  { path: 'tooltip', loadComponent: () => import('../pages/tooltip/tooltip.component').then(m => m.PageTooltipComponent) },
  { path: 'tree', loadComponent: () => import('../pages/tree/tree.component').then(m => m.PageTreeComponent) },
];
